version: "3.2"

services:

  migrations:
    command: bash -c "cd /mindsdb && python ./mindsdb/migrations/migrate.py"

    <<: &globalSettings
      build:
        context: ../
        dockerfile: ./docker/mindsdb.Dockerfile
      volumes:
        - type: bind
          source: ../
          target: /mindsdb
      environment:
        MINDSDB_STORAGE_DIR: "/mindsdb/var"

  mindsdb:
    # Copy global settings from migration above
    <<: *globalSettings
    restart: always
    ports:
      - '47334:47334'
      - '47335:47335'
      - '47336:47336'
        # command: bash -c "cd /mindsdb && python -m mindsdb --api=http,mysql,mongodb"
    command: bash -c "cd /mindsdb && python -m mindsdb --api=http,mysql,mongodb --config=tests/integration_tests/flows/config/docker_config.json"
    environment:
      MINDSDB_EXECUTOR_SERVICE_HOST: "executor"
      MINDSDB_EXECUTOR_SERVICE_PORT: "50052"
      MINDSDB_DB_SERVICE_HOST: "db_service"
      MINDSDB_DB_SERVICE_PORT: "50050"
      MINDSDB_DOCKER_ENV: "True"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
      FLASK_APP: "/mindsdb/mindsdb/__main__.py"
      SEPARATE_MIGRATIONS: "1"
    depends_on:
      - migrations
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:47334/api/util/ping"]
      interval: 30s
      timeout: 4s
      retries: 100

  lightwood:
    build:
      context: ../
      dockerfile: ./docker/ml_handler.Dockerfile
    depends_on:
      - mindsdb
    volumes:
      - type: bind
        source: ../
        target: /mindsdb
    environment:
      # have to share mindsdb database, because it doens't work without it
      REGISTRY_URL: "http://handler_discovery:5000"
      PORT: 50051
      HOST: "lightwood"
      MINDSDB_SERVICE_TYPE: "lightwood"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      REGISTRY_URL: "http://handler_discovery:5000"
      MINDSDB_DB_SERVICE_HOST: "db_service"
      MINDSDB_DB_SERVICE_PORT: "50050"

  huggingface:
    build:
      context: ../
      dockerfile: ./docker/ml_handler.Dockerfile
    depends_on:
      - mindsdb
    volumes:
      - type: bind
        source: ../
        target: /mindsdb
    environment:
      # have to share mindsdb database, because it doens't work without it
      PORT: 50053
      HOST: "huggingface"
      MINDSDB_SERVICE_TYPE: "huggingface"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      REGISTRY_URL: "http://handler_discovery:5000"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      MINDSDB_DB_SERVICE_HOST: "db_service"
      MINDSDB_DB_SERVICE_PORT: "50050"


  db_service:
    build:
      context: ../
      dockerfile: ./docker/db_handler.Dockerfile
    depends_on:
      - mindsdb
        # - mysql_db
    volumes:
      - type: bind
        source: ../
        target: /mindsdb
    environment:
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      PORT: "50050"

    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 120s
      timeout: 4s
      retries: 100

  executor:
    build:
      context: ../
      dockerfile: ./docker/executor.Dockerfile
    depends_on:
      - mindsdb
    environment:
      # have to share mindsdb database, because it doens't work without it
      # PORT: 5002
      PORT: 50052
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
        # BALANCER_URL: "http://balancer:80"
      MINDSDB_DB_SERVICE_HOST: "db_service"
      MINDSDB_DB_SERVICE_PORT: "50050"
        # MINDSDB_ML_SERVICE_HOST: "lightwood"
        # MINDSDB_ML_SERVICE_PORT: "50051"
      REGISTRY_URL: "http://handler_discovery:5000"
    volumes:
      - type: bind
        source: ../
        target: /mindsdb
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 120s
      timeout: 4s
      retries: 100

  handler_discovery:
    build:
      context: .
      dockerfile: ./handler_discovery.Dockerfile
    environment:
      PORT: 5000
